/* ECHS AP Practice Center 5.0 — independently audited gated release */
const ECHSOfficial={
  catalog:null,index:null,idMap:null,archiveIndex:null,archiveIdMap:null,
  chunkCache:new Map(),archiveChunkCache:new Map(),expansionQuestions:new Map(),expansionManifest:null,
  attemptKey:'echs_ap_v5_attempts',bookmarkKey:'echs_ap_v5_bookmarks',examKey:'echs_ap_v5_exam',settingsKey:'echs_ap_v5_settings',
  dataRoot:window.ECHS_DATA_ROOT||'data/student',archiveRoot:window.ECHS_ARCHIVE_DATA_ROOT||'data/student',assetRoot:window.ECHS_ASSET_ROOT||'',adminMode:Boolean(window.ECHS_ADMIN_MODE),
  join(base,path){return String(base||'').replace(/\/$/,'')+'/'+String(path||'').replace(/^\//,'')},
  async json(path){const r=await fetch(path);if(!r.ok)throw new Error(`Could not load ${path} (${r.status})`);return r.json()},
  async jsonOptional(path,fallback=null){try{return await this.json(path)}catch(e){console.warn(e.message);return fallback}},
  data(path){return this.join(this.dataRoot,path)},archiveData(path){return this.join(this.archiveRoot,path)},
  asset(path){if(!path)return'';if(/^(?:https?:|data:|blob:|\/)/i.test(path))return path;return this.join(this.assetRoot,path)},
  slug(v){return String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')},
  normalizeQuestion(raw,batch={}){
    const q={...raw};q.id=String(q.id||'').trim();q.course=q.course||'AP Calculus AB';q.courseId=q.courseId||this.slug(q.course);
    q.assessmentFamily=q.assessmentFamily||q.family||batch.label||batch.batchId||'Expansion batch';q.type=String(q.type||'mcq').toLowerCase();
    q.questionNumber=String(q.questionNumber||q.number||'');q.calculator=q.calculator||'no-calculator';q.prompt=q.prompt||'';
    q.choices=Array.isArray(q.choices)?q.choices:[];q.parts=Array.isArray(q.parts)?q.parts:[];q.media=Array.isArray(q.media)?q.media:[];
    q.classification=q.classification||{};q.classification.concepts=q.classification.concepts||[];q.classification.representations=q.classification.representations||[];
    q.classification.lessonIds=q.classification.lessonIds||q.classification.lessons||[];q.classification.learningObjectives=q.classification.learningObjectives||[];q.classification.skillCategories=q.classification.skillCategories||[];
    q.pedagogy=q.pedagogy||{};q.pedagogy.hints=q.pedagogy.hints||[];q.quality=q.quality||{};
    // Every import starts teacher-only. Promotion requires the independent release gate, never browser normalization.
    q.quality.productionStatus='teacher-archive-only';q.quality.needsReview=true;q.quality.transcriptionVerified=false;q.quality.answerVerified=false;
    q.quality.mathematicalVerificationPassed=false;q.quality.katexVerified=false;q.quality.mediaVerified=false;q.quality.mappingVerified=false;q.quality.studentReadyGatePassed=false;
    q.quality.reviewReasons=[...new Set([...(q.quality.reviewReasons||[]),'Imported record: independent teacher/source verification required before student release.'])];
    q.source=q.source||{};q.studentEligible=false;q.studentAccessible=false;q.studentReady=false;q.deploymentAccess='teacher-archive-only';
    q.contentStatus=(String(q.prompt).trim()&&(q.type!=='mcq'||q.choices.length))?'complete':'indexed-only';return q;
  },
  indexRowFromQuestion(q){
    const c=q.classification||{},p=q.pedagogy||{},quality=q.quality||{},source=q.source||{},concepts=c.concepts||[],repr=c.representations||[],lessons=c.lessonIds||c.lessons||[],los=c.learningObjectives||[],skills=c.skillCategories||[];
    const ready=quality.studentReadyGatePassed===true&&q.studentReady===true;
    return{id:q.id,course:q.course,courseId:q.courseId,family:q.assessmentFamily,type:q.type,year:q.year||null,form:q.form||'',number:q.questionNumber||'',section:q.section||'',calculator:q.calculator,
      unit:c.primaryUnit??null,unitLabel:c.primaryUnitLabel||(c.primaryUnit?`Unit ${c.primaryUnit}`:'Unclassified'),topic:c.primaryTopic||'Unclassified',topicCode:c.topicCode||'',lessons,learningObjectives:los,skills,
      concepts,representations:repr,difficulty:p.difficulty??null,difficultyLabel:p.difficultyLabel||'',officialStatus:source.officialStatus||q.officialStatus||'official',accessLevel:source.accessLevel||'school-internal',publicAllowed:Boolean(source.publicPublicationAllowed),
      readiness:ready?'student-ready':'teacher-archive-only',needsReview:!ready,answerVerified:Boolean(quality.answerVerified),mediaVerified:Boolean(quality.mediaVerified),mathVerified:Boolean(quality.mathematicalVerificationPassed),mappingVerified:Boolean(quality.mappingVerified),
      hasMedia:Boolean(q.media?.length),hasHints:Boolean(p.hints?.length),search:[q.id,q.course,q.year,c.primaryTopic,c.topicCode,...concepts,...repr,...los,...skills,q.courseId,q.assessmentFamily].filter(Boolean).join(' ').toLowerCase(),
      studentEligible:ready,studentAccessible:ready,studentReady:ready,deploymentAccess:ready?'student-ready':'teacher-archive-only',contentStatus:q.contentStatus||'complete',auditStatus:q.audit?.overallStatus||'',reviewRequired:!ready,mediaStatus:q.audit?.mediaStatus||'',mappingStatus:q.audit?.lessonMappingStatus||''};
  },
  async loadExpansions(){
    if(!this.adminMode)return;const manifest=await this.jsonOptional(this.data('expansions/manifest.json'),{batches:[]});this.expansionManifest=manifest;
    for(const entry of (manifest?.batches||[])){if(entry.enabled===false)continue;const batch=await this.jsonOptional(this.data('expansions/batches/'+entry.file),null);if(!batch)continue;
      for(const raw of (batch.questions||[])){const q=this.normalizeQuestion(raw,batch);if(!q.id)continue;this.expansionQuestions.set(q.id,q)}}
    if(this.expansionQuestions.size){const ids=new Set(this.expansionQuestions.keys());this.index=this.index.filter(r=>!ids.has(r.id));for(const q of this.expansionQuestions.values())this.index.push(this.indexRowFromQuestion(q));this.recalcCatalog()}
  },
  recalcCatalog(){
    const rows=this.index,c=this.catalog||{},countBy=fn=>rows.reduce((o,r)=>{const v=fn(r);if(v!==null&&v!==undefined&&v!=='')o[v]=(o[v]||0)+1;return o},{});
    c.schemaVersion='5.0.0';c.questionCount=rows.length;c.stats={...(c.stats||{}),questions:rows.length,mcq:rows.filter(r=>r.type==='mcq').length,frq:rows.filter(r=>r.type==='frq').length,withMedia:rows.filter(r=>r.hasMedia).length,withHints:rows.filter(r=>r.hasHints).length,answerVerified:rows.filter(r=>r.answerVerified).length,needsReview:rows.filter(r=>r.needsReview).length,studentEligible:rows.filter(r=>r.studentReady).length,studentAccessible:rows.filter(r=>r.studentReady).length,studentReady:rows.filter(r=>r.studentReady).length,fullyDigitized:rows.filter(r=>r.contentStatus==='complete').length,indexedOnly:rows.filter(r=>r.contentStatus!=='complete').length};
    c.courses=countBy(r=>r.course);c.types=countBy(r=>r.type);c.calculator=countBy(r=>r.calculator);c.units=countBy(r=>r.unit);c.readiness=countBy(r=>r.readiness);this.catalog=c;
  },
  async init(){if(!this.catalog)this.catalog=await this.json(this.data('catalog.json'));if(!this.index)this.index=await this.json(this.data('question-index.json'));if(!this.idMap)this.idMap=await this.json(this.data('id-map.json'));await this.loadExpansions();this.renderMath(document.body);return this},
  async initArchive(){await this.init();if(!this.archiveIndex)this.archiveIndex=await this.json(this.archiveData('archive-index.json'));if(!this.archiveIdMap)this.archiveIdMap=await this.json(this.archiveData('archive-id-map.json'));return this},
  async question(id){if(this.expansionQuestions.has(id))return this.expansionQuestions.get(id);const file=this.idMap[id];if(!file)return null;if(!this.chunkCache.has(file))this.chunkCache.set(file,(await this.json(this.data('questions/'+file))).questions||[]);return this.chunkCache.get(file).find(q=>q.id===id)||null},
  async questions(ids){const out=[],core=[];for(const id of ids){if(this.expansionQuestions.has(id))out.push(this.expansionQuestions.get(id));else core.push(id)}const groups={};core.forEach(id=>{const f=this.idMap[id];if(f)(groups[f]??=[]).push(id)});for(const [file,needed] of Object.entries(groups)){if(!this.chunkCache.has(file))this.chunkCache.set(file,(await this.json(this.data('questions/'+file))).questions||[]);const map=new Map(this.chunkCache.get(file).map(q=>[q.id,q]));needed.forEach(id=>{if(map.has(id))out.push(map.get(id))})}const order=new Map(ids.map((id,i)=>[id,i]));return out.sort((a,b)=>order.get(a.id)-order.get(b.id))},
  async archiveQuestion(id){await this.initArchive();const file=this.archiveIdMap[id];if(!file)return null;if(!this.archiveChunkCache.has(file))this.archiveChunkCache.set(file,(await this.json(this.archiveData('archive-questions/'+file))).questions||[]);return this.archiveChunkCache.get(file).find(q=>q.id===id)||null},
  esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))},fmt(v){return this.esc(v).replace(/\n/g,'<br>')},
  renderMath(root){if(!root)return;const run=()=>{try{if(window.renderMathInElement)renderMathInElement(root,{delimiters:[{left:'\\[',right:'\\]',display:true},{left:'\\(',right:'\\)',display:false}],throwOnError:false,strict:'warn',trust:false})}catch(e){console.warn('KaTeX render warning',e)}};if(window.renderMathInElement)run();else setTimeout(run,250)},
  params(){return new URLSearchParams(location.search)},shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b},uniq(a){return[...new Set(a.filter(x=>x!==null&&x!==undefined&&x!==''))]},
  attempts(){try{return JSON.parse(localStorage.getItem(this.attemptKey)||'[]')}catch{return[]}},
  saveAttempt(row){const valid=this.index.some(r=>r.id===row.id&&r.studentReady===true);if(!valid)return false;const a=this.attempts();a.push({...row,at:new Date().toISOString()});localStorage.setItem(this.attemptKey,JSON.stringify(a.slice(-10000)));return true},
  bookmarks(){try{return JSON.parse(localStorage.getItem(this.bookmarkKey)||'[]')}catch{return[]}},toggleBookmark(id){if(!this.index.some(r=>r.id===id&&r.studentReady===true))return false;const s=new Set(this.bookmarks());s.has(id)?s.delete(id):s.add(id);localStorage.setItem(this.bookmarkKey,JSON.stringify([...s]));return s.has(id)},settings(){try{return JSON.parse(localStorage.getItem(this.settingsKey)||'{}')}catch{return{}}},saveSettings(x){localStorage.setItem(this.settingsKey,JSON.stringify({...this.settings(),...x}))},rowLabel(r){return[r.year,r.course?.replace('AP Calculus ',''),r.type?.toUpperCase(),r.number||r.questionNumber].filter(Boolean).join(' · ')},
  isMCQ(q){return q?.type==='mcq'&&q.choices?.length===5},isStudentReady(q){return q?.studentReady===true||q?.quality?.studentReadyGatePassed===true},canViewFull(q){return this.adminMode||this.isStudentReady(q)},isIndexedOnly(q){return !this.isStudentReady(q)||q.contentStatus==='indexed-only'||!String(q.prompt||'').trim()||(q.type==='mcq'&&!q.choices?.length)},
  answerCorrect(q,response){if(!this.isStudentReady(q))return null;if(this.isMCQ(q))return String(response||'').toUpperCase()===String(q.answer||'').toUpperCase();const a=String(response||'').trim().toLowerCase(),accepted=(q.acceptedAnswers||[]).map(x=>String(x).trim().toLowerCase());return accepted.length?accepted.includes(a):null},
  chooseMedia(q){const rows=q?.media||[];return[...rows].filter(m=>m.path).sort((a,b)=>{const rank=x=>x.cropStatus==='question-region'?0:x.cropStatus==='full-page'?2:1;return rank(a)-rank(b)})},
  renderMedia(q,limit=2){const rows=this.chooseMedia(q).slice(0,limit);if(!rows.length)return'';return`<div class="questionMedia">${rows.map(m=>`<figure class="mediaFrame"><img loading="lazy" src="${this.esc(this.asset(m.path))}" alt="${this.esc(m.alt||'Mathematical source figure')}"><figcaption>${this.esc(m.caption||m.alt||'Source figure')}</figcaption></figure>`).join('')}</div>`},
  renderPrompt(q){if(!this.canViewFull(q)){return`<div class="notice indexedRecord"><strong>Indexed official record — not yet student-ready.</strong><p>${this.esc(q.archiveMessage||'This official record is indexed, but the complete independently verified student-ready question is not yet available.')}</p><div class="pillRow"><span class="pill wine">${this.esc(q.id)}</span><span class="pill red">${this.esc(q.audit?.overallStatus||'Review Required')}</span></div></div>`}const fac=q.facsimileAuthority&&q.media?.some(m=>m.path),text=fac?`<div class="notice"><strong>Source facsimile is authoritative.</strong> The verified source figure is shown below.</div>`:`<div class="prompt">${this.fmt(q.prompt)}</div>`;return text+this.renderMedia(q,fac?2:1)},
  renderChoices(q,selected,locked=false){if(!this.canViewFull(q)||!this.isMCQ(q))return'';const fac=q.facsimileAuthority&&q.media?.some(m=>m.path);return`<div class="choices">${q.choices.map(ch=>`<button class="choice ${selected===ch.label?'selected':''}" data-choice="${this.esc(ch.label)}" ${locked?'disabled':''}><span class="choiceLabel">${this.esc(ch.label)}</span><span>${fac?'Select choice '+this.esc(ch.label):this.fmt(ch.text)}</span></button>`).join('')}</div>`},
  renderParts(q){if(!this.canViewFull(q)||!q.parts?.length)return'';return q.parts.map(p=>`<section class="part"><div class="partLabel">${this.esc(p.label)} ${p.maxPoints?`· ${p.maxPoints} points`:''}</div><div class="partPrompt">${this.fmt(p.prompt)}</div><div class="responseArea control"><label>Your response</label><textarea rows="5" data-part="${this.esc(p.label)}"></textarea></div></section>`).join('')},
  metaPills(q){const cls=q.classification||{},quality=q.quality||{},ready=this.isStudentReady(q);return`<div class="pillRow"><span class="pill wine">${this.esc(q.course)}</span>${q.year?`<span class="pill gold">${q.year} · Q${this.esc(q.questionNumber)}</span>`:''}<span class="pill teal">${this.esc((q.type||'').toUpperCase())}</span><span class="pill">${this.esc(q.calculator)}</span>${cls.primaryUnit?`<span class="pill">Unit ${cls.primaryUnit}</span>`:''}${q.pedagogy?.difficultyLabel?`<span class="pill">${this.esc(q.pedagogy.difficultyLabel)}</span>`:''}<span class="pill ${ready?'teal':'red'}">${ready?'Student Ready':this.esc(q.audit?.overallStatus||'Review Required')}</span></div>`},
  filter(rows,f={}){const q=String(f.q||'').trim().toLowerCase(),topicCode=String(f.topicCode||'').trim(),lesson=String(f.lesson||'').trim(),lo=String(f.learningObjective||'').trim().toLowerCase(),skill=String(f.skill||'').trim().toLowerCase();return rows.filter(r=>{if(r.studentReady===false&&!this.adminMode)return false;if(f.course&&f.course!=='all'&&r.courseId!==f.course&&r.course!==f.course)return false;if(f.family&&f.family!=='all'&&r.family!==f.family)return false;if(f.year&&f.year!=='all'&&String(r.year)!==String(f.year))return false;if(f.type&&f.type!=='all'&&r.type!==f.type)return false;if(f.calculator&&f.calculator!=='all'&&r.calculator!==f.calculator)return false;if(f.unit&&f.unit!=='all'&&String(r.unit)!==String(f.unit))return false;if(topicCode&&String(r.topicCode)!==topicCode)return false;if(lesson&&!(r.lessons||[]).includes(lesson))return false;if(lo&&!(r.learningObjectives||[]).some(x=>String(x).toLowerCase().includes(lo)))return false;if(skill&&!(r.skills||[]).some(x=>String(x).toLowerCase()===skill))return false;if(f.topic&&f.topic!=='all'&&!String(r.topicCode||'').includes(f.topic)&&!String(r.topic||'').toLowerCase().includes(String(f.topic).toLowerCase()))return false;if(f.readiness&&f.readiness!=='all'&&r.readiness!==f.readiness)return false;if(f.difficulty&&f.difficulty!=='all'&&String(r.difficulty)!==String(f.difficulty))return false;if(f.media==='yes'&&!r.hasMedia)return false;if(f.media==='no'&&r.hasMedia)return false;if(q&&!String(r.search||'').includes(q))return false;return true})},
  smartSelect(rows,count){const readyRows=rows.filter(r=>r.studentReady===true),attempts=this.attempts().filter(a=>readyRows.some(r=>r.id===a.id)),byId=defaultMap(attempts,a=>a.id),byTopic=defaultMap(attempts,a=>a.topicCode||a.topic||'Unmapped');const scored=readyRows.map(r=>{const ia=byId.get(r.id)||[],ta=byTopic.get(r.topicCode||r.topic||'Unmapped')||[],wrong=ia.filter(a=>a.correct===false).length,correct=ia.filter(a=>a.correct===true).length,hints=ia.reduce((s,a)=>s+(a.hints||0),0),topicAcc=ta.length?ta.filter(a=>a.correct===true).length/ta.length:.55;return{r,w:1+wrong*4+Math.max(0,3-correct)+hints*1.5+(1-topicAcc)*4+Math.random()}}).sort((a,b)=>b.w-a.w);return scored.slice(0,count).map(x=>x.r)},
  exportJSON(name,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)},
  exportCSV(name,rows){if(!rows.length)return;const keys=Object.keys(rows[0]),csv=[keys.join(','),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replace(/"/g,'""')}"`).join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=name;a.click()}
};
function defaultMap(rows,key){const m=new Map();for(const r of rows){const k=key(r);if(!m.has(k))m.set(k,[]);m.get(k).push(r)}return m}
