/* ECHS Mathematics Learning System — Phase 2 local-first engine */
(function(){
"use strict";
const VERSION="2.0.0",DAY=86400000;
const KEYS={profile:"echs_learning_profile_v2",attempts:"echs_learning_events_v2",mastery:"echs_learning_mastery_v2",reviews:"echs_learning_reviews_v2",sessions:"echs_learning_sessions_v2",continue:"echs_learning_continue_v2",achievements:"echs_learning_achievements_v2",streak:"echs_learning_streak_v2",classes:"echs_learning_classes_v2",assignments:"echs_learning_assignments_v2",submissions:"echs_learning_submissions_v2",settings:"echs_learning_settings_v2"};
const COURSE_LABELS={"ap-calculus":"AP Calculus","ap-precalculus":"AP Precalculus","algebra-2":"Algebra 2 Concepts","ib-math-ai":"IB Mathematics AI","grade-9":"Grade 9 Pre-Precalculus",unassigned:"General Mathematics"};
const ACHIEVEMENTS=[
{id:"first-step",title:"First Step",description:"Answer your first practice question.",icon:"✦",test:s=>s.attempts>=1},
{id:"ten-questions",title:"Getting Started",description:"Answer 10 practice questions.",icon:"10",test:s=>s.attempts>=10},
{id:"fifty-questions",title:"Practice Builder",description:"Answer 50 practice questions.",icon:"50",test:s=>s.attempts>=50},
{id:"hundred-questions",title:"Century",description:"Answer 100 practice questions.",icon:"100",test:s=>s.attempts>=100},
{id:"five-hundred",title:"Deep Practice",description:"Answer 500 practice questions.",icon:"500",test:s=>s.attempts>=500},
{id:"streak-3",title:"Three-Day Streak",description:"Learn on three consecutive days.",icon:"🔥",test:s=>s.streak>=3},
{id:"streak-7",title:"Weekly Momentum",description:"Learn on seven consecutive days.",icon:"🔥",test:s=>s.streak>=7},
{id:"streak-30",title:"Monthly Discipline",description:"Learn on thirty consecutive days.",icon:"🏆",test:s=>s.streak>=30},
{id:"accuracy-80",title:"Accurate Thinker",description:"Reach at least 80% accuracy after 25 attempts.",icon:"✓",test:s=>s.attempts>=25&&s.accuracy>=80},
{id:"first-mastery",title:"Topic Master",description:"Master your first topic.",icon:"★",test:s=>s.mastered>=1},
{id:"five-masteries",title:"Mastery Five",description:"Master five topics.",icon:"★★★★★",test:s=>s.mastered>=5},
{id:"review-clear",title:"Review Complete",description:"Clear every due review after at least 20 attempts.",icon:"↻",test:s=>s.attempts>=20&&s.due===0}
];
const parse=(v,f)=>{try{return JSON.parse(v)??f}catch{return f}},read=(k,f)=>parse(localStorage.getItem(k),f),write=(k,v)=>(localStorage.setItem(k,JSON.stringify(v)),v);
const now=()=>new Date().toISOString(),dateKey=v=>{const d=v?new Date(v):new Date();return Number.isNaN(d.getTime())?"":d.toISOString().slice(0,10)};
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v)),uid=p=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,9)}`,uniq=a=>[...new Set(a.filter(Boolean))];
const escapeHTML=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function profile(){const p=read(KEYS.profile,null);return p||write(KEYS.profile,{schemaVersion:VERSION,id:uid("student"),name:"Student",grade:"",school:"ECHS",dailyGoal:10,createdAt:now()})}
function saveProfile(p={}){return write(KEYS.profile,{...profile(),...p,schemaVersion:VERSION,updatedAt:now()})}
function settings(){return read(KEYS.settings,{adaptive:true,dailyGoal:profile().dailyGoal||10,reviewReminder:true})}
function saveSettings(p={}){return write(KEYS.settings,{...settings(),...p,updatedAt:now()})}
const attempts=()=>read(KEYS.attempts,[]),masteryMap=()=>read(KEYS.mastery,{}),reviewMap=()=>read(KEYS.reviews,{}),sessions=()=>read(KEYS.sessions,[]),achievements=()=>read(KEYS.achievements,{}),streak=()=>read(KEYS.streak,{current:0,longest:0,lastActiveDate:"",activeDates:[]});
function inferCourse(q,c={}){if(c.course)return c.course;const s=String(q?.classification?.course_scope||"").toLowerCase();if(s.includes("precalculus"))return"ap-precalculus";if(s.includes("calculus"))return"ap-calculus";return new URLSearchParams(location.search).get("course")||"unassigned"}
function topicDescriptor(q,c={}){const x=q?.classification||{},s=q?.source||{},course=inferCourse(q,c),unit=String(c.unit??x.ap_unit??new URLSearchParams(location.search).get("unit")??"all"),topic=String(x.ap_topic||c.topic||s.section||s.skill_id||"general"),title=String(x.ap_topic_title||s.skill_title||s.section_title||q?.pool_title||`Unit ${unit}`),key=[course,unit,topic].map(v=>String(v).trim().toLowerCase()).join("::");return{key,course,unit,topic,title,courseLabel:COURSE_LABELS[course]||course}}
function updateStreak(at=now()){const s=streak(),today=dateKey(at);if(!today)return s;const dates=uniq([...(s.activeDates||[]),today]).sort().slice(-400),yesterday=dateKey(Date.now()-DAY);if(s.lastActiveDate!==today){s.current=s.lastActiveDate===yesterday?(s.current||0)+1:1;s.longest=Math.max(s.longest||0,s.current);s.lastActiveDate=today}s.activeDates=dates;return write(KEYS.streak,s)}
const level=s=>s>=80?"Mastered":s>=65?"Proficient":s>=45?"Developing":"Starting";
function recalc(r){const n=Math.max(0,r.attempts||0),a=n?(r.correct||0)/n:0,z=(r.recent||[]).slice(-8),ra=z.length?z.reduce((t,x)=>t+(x?1:0),0)/z.length:a,e=.55+.45*Math.min(n/8,1),score=Math.round(clamp((a*.4+ra*.6)*e*100,0,100));return{...r,score,accuracy:Math.round(a*100),level:level(score)}}
function updateMastery(q,ok,c={}){const d=topicDescriptor(q,c),all=masteryMap(),r=all[d.key]||{...d,attempts:0,correct:0,recent:[],score:0,accuracy:0,level:"Starting"};r.attempts++;if(ok)r.correct++;r.recent=[...(r.recent||[]),Boolean(ok)].slice(-12);r.lastAttemptAt=now();all[d.key]=recalc(r);write(KEYS.mastery,all);return all[d.key]}
const interval=b=>[0,1,3,7,14,30,60][clamp(b,0,6)];
function updateReview(q,ok,c={}){const all=reviewMap(),id=String(q?.id||"");if(!id)return null;const d=topicDescriptor(q,c),r=all[id]||{questionId:id,box:0,attempts:0,correct:0};r.attempts++;if(ok)r.correct++;r.box=ok?clamp((r.box||0)+1,1,6):0;r.unresolved=!ok;r.lastResult=Boolean(ok);r.lastAttemptAt=now();r.dueAt=new Date(Date.now()+(ok?interval(r.box):1)*DAY).toISOString();Object.assign(r,{course:d.course,unit:d.unit,topic:d.topic,topicKey:d.key,title:d.title,bankCode:q.bank_code||"",section:q.source?.section||"",promptText:String(q.prompt_text||"").slice(0,300)});all[id]=r;write(KEYS.reviews,all);return r}
function dueReviews({course=null,unit=null,limit=Infinity}={}){return Object.values(reviewMap()).filter(r=>new Date(r.dueAt||0).getTime()<=Date.now()).filter(r=>!course||r.course===course).filter(r=>unit==null||String(r.unit)===String(unit)).sort((a,b)=>new Date(a.dueAt)-new Date(b.dueAt)).slice(0,limit)}
function mistakes({course=null,unit=null,limit=Infinity}={}){return Object.values(reviewMap()).filter(r=>r.unresolved).filter(r=>!course||r.course===course).filter(r=>unit==null||String(r.unit)===String(unit)).sort((a,b)=>new Date(b.lastAttemptAt)-new Date(a.lastAttemptAt)).slice(0,limit)}
function masteryRows({course=null}={}){return Object.values(masteryMap()).filter(r=>!course||r.course===course).sort((a,b)=>a.score-b.score||b.attempts-a.attempts)}
function weakTopics(limit=5){return masteryRows().filter(r=>r.attempts>=2&&r.score<65).slice(0,limit)}
function summary(){const a=attempts(),correct=a.filter(x=>x.correct).length,m=Object.values(masteryMap()),s=streak();return{attempts:a.length,correct,accuracy:a.length?Math.round(correct/a.length*100):0,uniqueQuestions:new Set(a.map(x=>x.questionId||x.id)).size,topics:m.length,mastered:m.filter(x=>x.score>=80).length,proficient:m.filter(x=>x.score>=65).length,due:dueReviews().length,unresolved:mistakes().length,streak:s.current||0,longestStreak:s.longest||0,completedLessons:read("echs_math_complete",[]).length,bookmarkedLessons:read("echs_math_bookmarks",[]).length}}
function evaluateAchievements(){const s=summary(),all=achievements(),newly=[];ACHIEVEMENTS.forEach(x=>{if(!all[x.id]&&x.test(s)){all[x.id]={id:x.id,title:x.title,description:x.description,icon:x.icon,earnedAt:now()};newly.push(all[x.id])}});write(KEYS.achievements,all);if(newly.length)window.dispatchEvent(new CustomEvent("echs:achievement",{detail:{earned:newly}}));return newly}
function recordAttempt({question,correct,response="",mode="practice",sessionId=null,durationMs=null,context={}}){if(!question?.id)return null;const d=topicDescriptor(question,context),e={schemaVersion:VERSION,id:uid("attempt"),questionId:String(question.id),bankCode:question.bank_code||"",type:question.type||"",correct:Boolean(correct),response:String(response??""),mode,sessionId,durationMs:Number.isFinite(durationMs)?durationMs:null,assignmentId:context.assignmentId||null,...d,at:now()},a=attempts();a.push(e);write(KEYS.attempts,a.slice(-15000));updateMastery(question,Boolean(correct),context);updateReview(question,Boolean(correct),context);updateStreak(e.at);evaluateAchievements();window.dispatchEvent(new CustomEvent("echs:learning-attempt",{detail:e}));return e}
function markReviewResolved(id,resolved=true){const all=reviewMap();if(!all[id])return false;all[id].unresolved=!resolved;all[id].manuallyResolvedAt=resolved?now():null;write(KEYS.reviews,all);return true}
function startSession(meta={}){const r={schemaVersion:VERSION,id:uid("session"),type:meta.type||"practice",mode:meta.mode||"manual",status:"active",startedAt:now(),questionIds:meta.questionIds||[],answered:0,correct:0,...meta},a=sessions();a.push(r);write(KEYS.sessions,a.slice(-1000));return r}
function patchSession(id,p={}){const a=sessions(),i=a.findIndex(x=>x.id===id);if(i<0)return null;a[i]={...a[i],...p,updatedAt:now()};write(KEYS.sessions,a);return a[i]}
const endSession=(id,p={})=>patchSession(id,{...p,status:"completed",endedAt:now()}),activeSession=id=>sessions().find(x=>x.id===id&&x.status==="active")||null,recentSessions=(limit=10)=>sessions().slice().sort((a,b)=>new Date(b.startedAt)-new Date(a.startedAt)).slice(0,limit);
function setContinue(s){if(!s){localStorage.removeItem(KEYS.continue);return null}return write(KEYS.continue,{schemaVersion:VERSION,...s,updatedAt:now()})}
const getContinue=()=>read(KEYS.continue,null),clearContinue=()=>localStorage.removeItem(KEYS.continue);
const questionDifficulty=q=>{const v=Number(q?.metadata?.difficulty);return Number.isFinite(v)&&v>=1&&v<=3?v:2};
function adaptiveTarget(q){const d=topicDescriptor(q),s=masteryMap()[d.key]?.score??35;return s<40?1:s<72?2:3}
function adaptiveScore(q,{excludedIds=[],lastCorrect=null}={}){if(excludedIds.includes(String(q.id)))return-Infinity;const d=topicDescriptor(q),m=masteryMap()[d.key],r=reviewMap()[q.id],difficulty=questionDifficulty(q);let target=adaptiveTarget(q),score=0;if(lastCorrect===true)target=Math.min(3,target+1);if(lastCorrect===false)target=Math.max(1,target-1);if(r?.unresolved)score+=80;if(r&&new Date(r.dueAt||0)<=new Date())score+=65;if(!r)score+=28;score+=(100-(m?.score??30))*.65;score-=Math.abs(difficulty-target)*22;return score+Math.random()*18}
function selectAdaptive(qs,count=10,o={}){const excluded=[...(o.excludedIds||[])],out=[];for(let i=0;i<count;i++){const ranked=qs.map(q=>({q,score:adaptiveScore(q,{...o,excludedIds:excluded})})).filter(x=>Number.isFinite(x.score)).sort((a,b)=>b.score-a.score);if(!ranked.length)break;const top=ranked.slice(0,Math.min(8,ranked.length)),q=top[Math.floor(Math.random()*top.length)].q;out.push(q);excluded.push(String(q.id))}return out}
function dailyPlan(){const p=profile(),goal=Number(settings().dailyGoal||p.dailyGoal||10),today=dateKey(),todayAttempts=attempts().filter(r=>dateKey(r.at)===today).length,due=dueReviews({limit:20}),weak=weakTopics(3),cont=getContinue(),items=[];if(cont)items.push({type:"continue",title:"Continue where you stopped",detail:cont.label||"Resume your last activity",href:cont.url||"practice.html?resume=1",priority:100});if(due.length)items.push({type:"review",title:`Review ${Math.min(due.length,10)} due question${due.length===1?"":"s"}`,detail:"Spaced review is ready now.",href:"practice.html?mode=review&autostart=1",priority:90});if(weak.length)items.push({type:"adaptive",title:`Strengthen ${weak[0].title}`,detail:`Current mastery ${weak[0].score}%.`,href:`practice.html?course=${encodeURIComponent(weak[0].course)}&unit=${encodeURIComponent(weak[0].unit)}&mode=adaptive&autostart=1`,priority:80});if(todayAttempts<goal)items.push({type:"goal",title:`Complete ${goal-todayAttempts} more question${goal-todayAttempts===1?"":"s"} today`,detail:`Daily goal: ${goal}.`,href:"practice.html?mode=adaptive&autostart=1",priority:70});if(!items.length)items.push({type:"complete",title:"Today's plan is complete",detail:"Choose a challenge set or continue a lesson.",href:"practice.html?mode=adaptive",priority:1});return{goal,todayAttempts,progress:goal?Math.min(100,Math.round(todayAttempts/goal*100)):0,items:items.sort((a,b)=>b.priority-a.priority)}}
const earnedAchievements=()=>{const e=achievements();return ACHIEVEMENTS.map(x=>({...x,earned:e[x.id]||null}))};
function exportStudentReport(){const p=profile();return{schema:"echs-learning-report",schemaVersion:VERSION,generatedAt:now(),student:{id:p.id,name:p.name,grade:p.grade,school:p.school},summary:summary(),mastery:masteryRows(),dueReviews:dueReviews({limit:100}).map(({questionId,course,unit,topic,title,dueAt,unresolved})=>({questionId,course,unit,topic,title,dueAt,unresolved})),weakTopics:weakTopics(10),achievements:Object.values(achievements()),recentSessions:recentSessions(25).map(({id,type,mode,status,startedAt,endedAt,answered,correct,score,assignmentId})=>({id,type,mode,status,startedAt,endedAt,answered,correct,score,assignmentId}))}}
function downloadJSON(name,data){const b=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
const exportReport=()=>{const r=exportStudentReport();downloadJSON(`ECHS-learning-report-${dateKey()}.json`,r);return r};
function migrateLegacyAttempts(){if(attempts().length)return 0;const old=read("echs_qbank_attempts_v20",[]);if(!Array.isArray(old)||!old.length)return 0;const events=[],mastery={...masteryMap()},reviews={...reviewMap()};old.slice(-15000).forEach(r=>{const course=r.course||"unassigned",unit=String(r.unit||"all"),topic=String(r.topic||r.section||"general"),key=[course,unit,topic].map(v=>String(v).toLowerCase()).join("::"),title=r.lesson||r.section||`Unit ${unit}`;events.push({schemaVersion:VERSION,id:uid("legacy"),questionId:String(r.id||""),bankCode:r.bank_code||"",type:r.type||"",correct:Boolean(r.correct),response:String(r.response||""),mode:"legacy",key,course,unit,topic,title,courseLabel:COURSE_LABELS[course]||course,at:r.at||now(),migrated:true});const m=mastery[key]||{key,course,unit,topic,title,courseLabel:COURSE_LABELS[course]||course,attempts:0,correct:0,recent:[]};m.attempts++;if(r.correct)m.correct++;m.recent=[...(m.recent||[]),Boolean(r.correct)].slice(-12);m.lastAttemptAt=r.at||now();mastery[key]=recalc(m);if(r.id){const v=reviews[r.id]||{questionId:String(r.id),box:0,attempts:0,correct:0};v.attempts++;if(r.correct)v.correct++;v.box=r.correct?Math.max(1,v.box||0):0;v.unresolved=!r.correct;v.lastAttemptAt=r.at||now();v.dueAt=new Date(new Date(r.at||Date.now()).getTime()+(r.correct?interval(v.box):1)*DAY).toISOString();Object.assign(v,{course,unit,topic,topicKey:key,title,bankCode:r.bank_code||"",section:r.section||""});reviews[r.id]=v}});write(KEYS.attempts,events);write(KEYS.mastery,mastery);write(KEYS.reviews,reviews);old.forEach(r=>updateStreak(r.at||now()));evaluateAchievements();return events.length}
function resetLearningData({keepProfile=true,keepTeacher=true}={}){const keep=new Set();if(keepProfile)keep.add(KEYS.profile);if(keepTeacher)[KEYS.classes,KEYS.assignments,KEYS.submissions].forEach(k=>keep.add(k));Object.values(KEYS).forEach(k=>{if(!keep.has(k))localStorage.removeItem(k)})}
const api={VERSION,KEYS,COURSE_LABELS,ACHIEVEMENTS,escapeHTML,uid,dateKey,profile,saveProfile,settings,saveSettings,attempts,masteryMap,reviewMap,sessions,achievements,streak,topicDescriptor,recordAttempt,summary,updateStreak,evaluateAchievements,dueReviews,mistakes,markReviewResolved,masteryRows,weakTopics,startSession,patchSession,endSession,activeSession,recentSessions,setContinue,getContinue,clearContinue,selectAdaptive,adaptiveScore,adaptiveTarget,questionDifficulty,dailyPlan,earnedAchievements,exportStudentReport,exportReport,downloadJSON,resetLearningData,migrateLegacyAttempts,read,write};
window.ECHSLearning=api;migrateLegacyAttempts();
window.addEventListener("echs:achievement",e=>{const a=e.detail?.earned||[];if(a.length&&window.ECHSPlatform?.toast)window.ECHSPlatform.toast(`Achievement unlocked: ${a.map(x=>x.title).join(", ")}`)});
})();