/* ECHS Mistake Bank */
(function(){
  "use strict";
  const $=id=>document.getElementById(id),esc=ECHSLearning.escapeHTML,labels=ECHSLearning.COURSE_LABELS;
  const allRows=()=>Object.values(ECHSLearning.reviewMap()).sort((a,b)=>new Date(b.lastAttemptAt)-new Date(a.lastAttemptAt));
  const due=row=>new Date(row.dueAt||0).getTime()<=Date.now();
  function stats(){const rows=allRows(),mistakes=rows.filter(row=>row.unresolved),dueRows=rows.filter(due),reviewed=rows.filter(row=>(row.attempts||0)>1),recovered=rows.filter(row=>!row.unresolved&&(row.attempts||0)>1);$("heroMistakes").textContent=mistakes.length.toLocaleString();$("heroDue").textContent=dueRows.length.toLocaleString();$("heroReviewed").textContent=reviewed.length.toLocaleString();$("heroRecovered").textContent=recovered.length.toLocaleString();}
  function fillFilters(){const rows=allRows(),course=$("courseFilter").value||"all",unit=$("unitFilter").value||"all";const courses=[...new Set(rows.map(row=>row.course).filter(Boolean))].sort();$("courseFilter").innerHTML='<option value="all">All courses</option>'+courses.map(value=>`<option value="${esc(value)}" ${value===course?"selected":""}>${esc(labels[value]||value)}</option>`).join("");const filtered=rows.filter(row=>course==="all"||row.course===course);const units=[...new Set(filtered.map(row=>String(row.unit)).filter(Boolean))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));$("unitFilter").innerHTML='<option value="all">All units</option>'+units.map(value=>`<option value="${esc(value)}" ${value===unit?"selected":""}>Unit ${esc(value)}</option>`).join("");}
  function filteredRows(){const view=$("viewFilter").value,course=$("courseFilter").value,unit=$("unitFilter").value;return allRows().filter(row=>view==="all"||(view==="mistakes"?row.unresolved:due(row))).filter(row=>course==="all"||row.course===course).filter(row=>unit==="all"||String(row.unit)===unit);}
  function render(){stats();fillFilters();const rows=filteredRows();$("reviewList").innerHTML=rows.length?rows.map(row=>{const state=row.unresolved?'<span class="statusBadge danger">Unresolved</span>':due(row)?'<span class="statusBadge warning">Due</span>':'<span class="statusBadge good">Recovered</span>';return`<article class="reviewRow" data-id="${esc(row.questionId)}"><div><strong>${esc(row.title||"Practice question")}</strong><p>${esc(row.promptText||"Question details are available in Practice Studio.")}</p><div class="reviewMeta"><span class="pill">${esc(labels[row.course]||row.course)}</span><span class="pill">Unit ${esc(row.unit)}</span><span class="pill">${row.attempts||0} attempts</span><span class="pill">Box ${row.box||0}</span><span class="pill">Due ${new Date(row.dueAt).toLocaleDateString()}</span>${state}</div></div><div class="reviewActions"><a class="button ghost" href="practice.html?course=${encodeURIComponent(row.course)}&unit=${encodeURIComponent(row.unit)}&mode=mistakes&autostart=1">Practise</a><button class="button ghost" data-resolve="${esc(row.questionId)}">${row.unresolved?"Mark resolved":"Reopen"}</button></div></article>`;}).join(""):`<div class="emptyLearning"><h2>Nothing to review here</h2><p>Incorrect questions will appear automatically after practice or tests.</p><a class="button wine" href="practice.html?mode=adaptive">Start adaptive practice</a></div>`;document.querySelectorAll("[data-resolve]").forEach(button=>button.onclick=()=>{const row=ECHSLearning.reviewMap()[button.dataset.resolve];ECHSLearning.markReviewResolved(button.dataset.resolve,row?.unresolved);render();});const params=new URLSearchParams({mode:$("viewFilter").value==="due"?"review":"mistakes",autostart:"1"});if($("courseFilter").value!=="all")params.set("course",$("courseFilter").value);if($("unitFilter").value!=="all")params.set("unit",$("unitFilter").value);$("startReview").href=`practice.html?${params}`;}
  $("viewFilter").onchange=render;$("courseFilter").onchange=()=>{$("unitFilter").value="all";render();};$("unitFilter").onchange=render;$("exportReview").onclick=()=>ECHSLearning.downloadJSON(`ECHS-review-list-${ECHSLearning.dateKey()}.json`,{schema:"echs-review-list",generatedAt:new Date().toISOString(),student:ECHSLearning.profile(),items:filteredRows()});render();
})();