document.querySelector('.navLink[href="review.html"]').classList.add('active');
const STORE='echs_qbank_unit1_topic_review_v1';
const UI={shell:document.getElementById('reviewShell'),summary:document.getElementById('summary'),filter:document.getElementById('filter'),jump:document.getElementById('jump'),prev:document.getElementById('prev'),next:document.getElementById('next'),position:document.getElementById('position'),export:document.getElementById('export'),import:document.getElementById('import'),clear:document.getElementById('clear')};
let queue=null,index=0,decisions={};
function read(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')||{};}catch{return{};}}
function save(){localStorage.setItem(STORE,JSON.stringify(decisions));}
function rows(){const all=queue?.questions||[];if(UI.filter.value==='approved')return all.filter(x=>decisions[x.question.id]?.approved);if(UI.filter.value==='pending')return all.filter(x=>!decisions[x.question.id]?.approved);return all;}
function actionFromValue(v){if(v==='unit1_no_topic'||v==='remove_unit1')return v;return 'set_topic';}
function topicValue(item){const d=decisions[item.question.id];if(d)return d.action==='set_topic'?d.topic:d.action;return item.editorial.editorial_topic||'unit1_no_topic';}
function decision(item){const id=item.question.id;return decisions[id]||{id,action:actionFromValue(topicValue(item)),topic:item.editorial.editorial_topic||null,note:'',approved:false};}
function setDecision(item,patch){const id=item.question.id;const current=decision(item);decisions[id]={...current,...patch,id};save();renderSummary();renderJump();}
function renderSummary(){const total=queue?.count||0,approved=Object.values(decisions).filter(d=>d.approved).length,pending=total-approved;UI.summary.innerHTML=`<div class="stat"><b>${total}</b><span>Editorial decisions to audit</span></div><div class="stat"><b>${approved}</b><span>Teacher-approved locally</span></div><div class="stat"><b>${pending}</b><span>Pending</span></div><div class="stat"><b>${Math.round(approved/Math.max(total,1)*100)}%</b><span>Review completion</span></div>`;}
function renderJump(){const list=rows();UI.jump.innerHTML=list.map((item,i)=>`<option value="${i}" ${i===index?'selected':''}>${i+1}. ${ECHSBank.escape(item.question.id)}${decisions[item.question.id]?.approved?' ✓':''}</option>`).join('');}
function choiceHtml(q){if(!q.choices?.length)return'';return`<div class="reviewChoices">${q.choices.map((c,i)=>`<div class="reviewChoice ${(q.correct_choice_ids||[]).includes(c.id)?'answer':''}"><span class="choiceLabel">${String.fromCharCode(65+i)}</span><span>${c.html}</span>${(q.correct_choice_ids||[]).includes(c.id)?'<b>Key</b>':''}</div>`).join('')}</div>`;}
function render(){const list=rows();if(!list.length){UI.shell.innerHTML='<div class="empty">No items match this filter.</div>';UI.position.textContent='0 / 0';renderJump();return;}index=Math.max(0,Math.min(index,list.length-1));const item=list[index],q=item.question,e=item.editorial,d=decision(item),value=topicValue(item);const opts=Object.entries(queue.topics).map(([id,title])=>`<option value="${id}" ${value===id?'selected':''}>${id} · ${ECHSBank.escape(title)}</option>`).join('');UI.shell.innerHTML=`<article class="questionCard teacherReviewCard"><div class="pillRow"><span class="pill wine">${ECHSBank.escape(q.id)}</span><span class="pill teal">${ECHSBank.escape(q.bank_code)}</span><span class="pill">Section ${ECHSBank.escape(q.source?.section||'—')}</span><span class="pill gold">Original ${ECHSBank.escape(e.original_topic||'none')} · ${ECHSBank.escape(e.original_confidence||'')}</span>${d.approved?'<span class="pill ok">Teacher approved</span>':'<span class="pill bad">Pending</span>'}</div><h2>${ECHSBank.escape(q.source?.skill_title||q.source?.section_title||'Question')}</h2><div class="prompt">${q.prompt_html}</div>${choiceHtml(q)}<div class="editorialNote"><strong>Editorial rationale</strong><p>${ECHSBank.escape(e.rationale)}</p></div><div class="reviewDecision"><div class="control"><label>Approved AP placement</label><select id="topicSelect">${opts}<option value="unit1_no_topic" ${value==='unit1_no_topic'?'selected':''}>Unit 1 enrichment · no official topic</option><option value="remove_unit1" ${value==='remove_unit1'?'selected':''}>Remove from AP Unit 1</option></select></div><div class="control"><label>Teacher note</label><textarea id="note" rows="3" placeholder="Optional rationale or correction…">${ECHSBank.escape(d.note||'')}</textarea></div><label class="approveCheck"><input type="checkbox" id="approved" ${d.approved?'checked':''}> I approve this placement for ECHS.</label></div><div class="questionFooter"><button class="button ghost" id="prevCard">Previous</button><button class="button wine" id="saveNext">Save and next</button></div></article>`;UI.position.textContent=`${index+1} / ${list.length}`;UI.prev.disabled=index===0;UI.next.disabled=index===list.length-1;renderJump();
const commit=(goNext=false)=>{const v=document.getElementById('topicSelect').value,action=actionFromValue(v);setDecision(item,{action,topic:action==='set_topic'?v:null,note:document.getElementById('note').value.trim(),approved:document.getElementById('approved').checked});if(goNext){index=Math.min(index+1,rows().length-1);render();}};document.getElementById('topicSelect').onchange=()=>commit(false);document.getElementById('note').onchange=()=>commit(false);document.getElementById('approved').onchange=()=>commit(false);document.getElementById('saveNext').onclick=()=>commit(true);document.getElementById('prevCard').onclick=()=>{index=Math.max(0,index-1);render();};}
function exportDecisions(){const all=(queue?.questions||[]).map(item=>decision(item)).filter(d=>d.approved);const payload={format:'echs-topic-overrides-v1',source_version:queue.version,exported_at:new Date().toISOString(),overrides:all};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='echs-unit1-topic-overrides.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
UI.prev.onclick=()=>{index=Math.max(0,index-1);render();};UI.next.onclick=()=>{index=Math.min(index+1,rows().length-1);render();};UI.filter.onchange=()=>{index=0;render();};UI.jump.onchange=()=>{index=Number(UI.jump.value)||0;render();};UI.export.onclick=exportDecisions;UI.clear.onclick=()=>{if(confirm('Clear all locally saved teacher-review decisions?')){decisions={};localStorage.removeItem(STORE);index=0;renderSummary();render();}};UI.import.onchange=async()=>{const file=UI.import.files?.[0];if(!file)return;try{const payload=JSON.parse(await file.text()),list=payload.overrides||[];for(const row of list){if(row?.id)decisions[row.id]=row;}save();renderSummary();render();}catch(e){alert('Could not import this JSON file: '+e.message);}UI.import.value='';};
(async()=>{try{const response=await fetch('data/review/unit1_teacher_review_queue.json');if(!response.ok)throw new Error('Could not load review queue');queue=await response.json();decisions=read();renderSummary();render();}catch(e){UI.shell.innerHTML=`<div class="notice">${ECHSBank.escape(e.message)}. Run the folder through HTTP.</div>`;}})();